### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by steveprutz** [manifestoforscalingagility/ManifestoForScalingAgility.github.io#21]
This may not be part of the codebase, but a favicon for scalingmanifesto.org would be a nice-to-have. See attached icon idea.
![mtn_32_favicon](https://github.com/manifestoforscalingagility/ManifestoForScalingAgility.github.io/assets/16653971/7f49d346-610e-43f7-b76f-f53ae864fb4d)

**Comment by DaneWeber** [comment]
Thanks. Good idea.

Do you know the use rights to the image you shared? Do you happen to have files in the right format?

Also, any chance you know how to add a favicon to GitHub pages?

**Comment by steveprutz** [comment]
> Thanks. Good idea.
> 
> Do you know the use rights to the image you shared? Do you happen to have files in the right format?
> 
> Also, any chance you know how to add a favicon to GitHub pages?

1. The attached image is my own work, inspired by the Mountain emoji, circa 2015. Feel free to use or modify. The format (PNG) is supported in HTML (e.g., `<link rel="shortcut icon" type="image/png" href="favicon.png">`)
2. Adding a favicon to github.io is as easy as uploading the PNG, and then referencing it in the HTML header. (see https://stackoverflow.com/questions/35037482/favicon-with-github-pages)

**Comment by DaneWeber** [comment]
Are you interested in creating a PR with the line added to [_layouts/default.html](https://github.com/manifestoforscalingagility/ManifestoForScalingAgility.github.io/blob/master/_layouts/default.html) and the file added in either the root or assets/images?

If not, I can probably get to it eventually, but "eventually" can be quite a while for me.

**Comment by steveprutz** [comment]
PR #22
