### ISSUE TITLE
Colours of "Principles" fonts difficult to see

### ISSUE THREAD

**Issue by daverooneyca** [manifestoforscalingagility/ManifestoForScalingAgility.github.io#7]
The gray on gray font of the Principles section is somewhat difficult to see, especially for those of us who aren't spring chickens anymore! 😄  Some better contrast between the text and the background would be appreciated.

**Comment by DaneWeber** [comment]
On my personal backlog: higher contrast for text. Test on various devices.

I'd love any volunteers who want to help.
